"""Generate the Tier-4 (WS10) training and evaluation configs from the v4 ones.

Every generated file is the corresponding v4 file with the MINIMUM changes the
experiment needs, so a diff against its source shows exactly what differs. Run
once; the outputs are committed. Re-running overwrites them identically.

  WS10a  learned optimal attack on a FROZEN MM (Zhang et al. 2021, ATLA)
         env   adversarial_mm_v4opt_<arm>.json   = the arm's EVAL env json with a
               cost-free adversary (c_fill = c_reg = kappa = p_detect = 0), gate
               always on, budget 1e7, observe_victim = true
         train kaya_v4opt_<arm>.yaml             FREEZE_MM, MM_INIT_FROM the v4 arm
         eval  eval_2024_test_v4opt_<arm>.yaml
  WS10b  shuffled-label auxiliary head (random-label control; Zheng et al. 2021)
         train kaya_v4_config8_shuffled_noobs.yaml   config7 env + DETECTION_LABEL_MODE
         eval  eval_2024_test_v4_config8.yaml
  WS10c  recurrent market maker (history-conditioned policy; ATLA)
         train kaya_v4r_config{1,3}_*.yaml       MM_RECURRENT
         eval  eval_2024_test_v4r_config{1,3}.yaml

    python make_tier4_configs.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ENV = ROOT / "config" / "env_configs"
RL = ROOT / "config" / "rl_configs"

# v4 arm -> (config number, v4 project suffix)
V4 = {"baseline": (1, "config1_baseline"), "adversarial": (2, "config2_adversarial"),
      "full": (3, "config3_full")}
OPT_ARMS = ("baseline", "adversarial", "full")
OPT_UPDATES = 500                       # adversary-only updates (v4 co-training gave ~501)
OPT_TIMESTEPS = OPT_UPDATES * 512 * 16  # = 4,096,000; pass on the sbatch line
ATTACK_SPOOF = {"c_fill": 0.0, "c_reg": 0.0, "kappa": 0.0, "p_detect": 0.0,
                "attack_on_prob": 1.0, "attack_off_prob": 0.0,
                "budget_per_episode": 1.0e7, "observe_victim": True, "victim_obs_dim": 45}


def _sub(text: str, key: str, value: str) -> str:
    pat = re.compile(rf'^"{key}":.*$', re.M)
    if not pat.search(text):
        raise KeyError(f"{key} not found")
    return pat.sub(f'"{key}": {value}', text, count=1)


def _header(text: str, lines: list[str]) -> str:
    return "\n".join("# " + ln if ln else "#" for ln in lines) + "\n#\n" + text


def _eval_env_json(n: int) -> str:
    y = (RL / f"eval_2024_test_v4_config{n}.yaml").read_text()
    return re.search(r'^"ENV_CONFIG":\s*"([^"]+)"', y, re.M).group(1)


def ws10a() -> list[Path]:
    out = []
    for arm in OPT_ARMS:
        n, suffix = V4[arm]
        src_env = _eval_env_json(n)               # the env the arm is EVALUATED in
        d = json.loads((ROOT / src_env).read_text())
        d["dict_of_agents_configs"]["Spoofing"].update(ATTACK_SPOOF)
        env_path = ENV / f"adversarial_mm_v4opt_{arm}.json"
        env_path.write_text(json.dumps(d, indent=2) + "\n", newline=chr(10))
        out.append(env_path)
        rel_env = f"config/env_configs/{env_path.name}"

        t = (RL / f"kaya_v4_{suffix}.yaml").read_text()
        t = _sub(t, "ENV_CONFIG", f'"{rel_env}"')
        t = _sub(t, "PROJECT", f'"v4opt_{arm}"')
        t = _sub(t, "ANNEAL_TOTAL_UPDATES", str(2 * OPT_UPDATES))
        t += ("\n# WS10a switches (ippo_adversarial.py): the MM is loaded from the trained v4\n"
              "# arm and never updated; every update trains the adversary.\n"
              '"FREEZE_MM": true\n'
              f'"MM_INIT_FROM": "v4_{suffix}/seed_{{SEED}}@1002"\n')
        t = _header(t, [
            f"WS10a LEARNED OPTIMAL ATTACK on the frozen v4 '{arm}' market maker. EXPLORATORY.",
            f"Generated by make_tier4_configs.py from kaya_v4_{suffix}.yaml.",
            f"Env = {src_env} (the arm's eval env) + cost-free, always-on, 1e7-budget,",
            "victim-observing adversary. ANNEAL_TOTAL_UPDATES = 2 x updates because the",
            "schedule halves it for alternating freezes, and here the adversary updates every step.",
            "",
            f"  sbatch --time=12:00:00 --array=0-19%10 slurm_cpu_sweep.sh kaya_v4opt_{arm} TOTAL_TIMESTEPS={OPT_TIMESTEPS}",
        ])
        p = RL / f"kaya_v4opt_{arm}.yaml"
        p.write_text(t, newline=chr(10))
        out.append(p)

        e = (RL / f"eval_2024_test_v4_config{n}.yaml").read_text()
        e = _sub(e, "ENV_CONFIG", f'"{rel_env}"')
        e = _sub(e, "PROJECT", f'"v4opt_{arm}"')
        e = _header(e, [f"WS10a eval of v4opt_{arm} (eval_learned_attack.py). Generated by "
                        f"make_tier4_configs.py from eval_2024_test_v4_config{n}.yaml."])
        p = RL / f"eval_2024_test_v4opt_{arm}.yaml"
        p.write_text(e, newline=chr(10))
        out.append(p)
    return out


def ws10b() -> list[Path]:
    t = (RL / "kaya_v4_config7_detection_noobs.yaml").read_text()
    t = _sub(t, "PROJECT", '"v4_config8_shuffled_noobs"')
    t += ("\n# WS10b switch: permute the MM oracle labels across (time x actors) every\n"
          "# update -- same base rate, no obs-label relation.\n"
          '"DETECTION_LABEL_MODE": "shuffled"\n')
    t = _header(t, [
        "WS10b SHUFFLED-LABEL auxiliary head (arm H). EXPLORATORY.",
        "Generated by make_tier4_configs.py from kaya_v4_config7_detection_noobs.yaml:",
        "same env (head trained, output NOT in the policy obs), same everything, but the",
        "BCE labels are shuffled. H vs G(detection_noobs) isolates label content; H vs",
        "B(adversarial) isolates 'any auxiliary BCE loss'.",
        "",
        "  sbatch --time=12:00:00 --array=0-19%10 slurm_cpu_sweep.sh kaya_v4_config8_shuffled_noobs",
    ])
    p1 = RL / "kaya_v4_config8_shuffled_noobs.yaml"
    p1.write_text(t, newline=chr(10))
    e = (RL / "eval_2024_test_v4_config7.yaml").read_text()
    e = _sub(e, "PROJECT", '"v4_config8_shuffled_noobs"')
    e = _header(e, ["WS10b eval of v4_config8_shuffled_noobs. Generated by make_tier4_configs.py "
                    "from eval_2024_test_v4_config7.yaml (same env)."])
    p2 = RL / "eval_2024_test_v4_config8.yaml"
    p2.write_text(e, newline=chr(10))
    return [p1, p2]


def ws10c() -> list[Path]:
    out = []
    for arm in ("baseline", "full"):
        n, suffix = V4[arm]
        t = (RL / f"kaya_v4_{suffix}.yaml").read_text()
        t = _sub(t, "PROJECT", f'"v4r_{suffix}"')
        t += "\n# WS10c switch: GRU between SharedEncoder and PolicyHead.\n\"MM_RECURRENT\": true\n"
        t = _header(t, [
            f"WS10c RECURRENT market maker, '{arm}' arm. EXPLORATORY.",
            f"Generated by make_tier4_configs.py from kaya_v4_{suffix}.yaml.",
            "",
            f"  sbatch --time=16:00:00 --array=0-19%10 slurm_cpu_sweep.sh kaya_v4r_{suffix}",
        ])
        p = RL / f"kaya_v4r_{suffix}.yaml"
        p.write_text(t, newline=chr(10))
        out.append(p)
        e = (RL / f"eval_2024_test_v4_config{n}.yaml").read_text()
        e = _sub(e, "PROJECT", f'"v4r_{suffix}"')
        e += "\n\"MM_RECURRENT\": true\n"
        e = _header(e, [f"WS10c eval of v4r_{suffix}. Generated by make_tier4_configs.py "
                        f"from eval_2024_test_v4_config{n}.yaml."])
        p = RL / f"eval_2024_test_v4r_config{n}.yaml"
        p.write_text(e, newline=chr(10))
        out.append(p)
    return out


def main() -> int:
    for p in ws10a() + ws10b() + ws10c():
        print("wrote", p.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
